// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection
open System.Runtime.CompilerServices

[<assembly: InternalsVisibleTo("GraphBLAS-sharp.Tests")>]
[<assembly: AssemblyTitleAttribute("GraphBLAS-sharp")>]
[<assembly: AssemblyProductAttribute("GraphBLAS-sharp")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate", "2017-03-17T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadataAttribute("GitHash", "bb8964b54bee133e9af64d316dc2cfee16df7f72")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GraphBLAS-sharp"
    let [<Literal>] AssemblyProduct = "GraphBLAS-sharp"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2017-03-17T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "bb8964b54bee133e9af64d316dc2cfee16df7f72"
